### PR TITLE
Fixed bedtools tmp paths to match extracted archive content

### PR DESCRIPTION
**Pull request by nuwang**

### CODE REVIEW

**Comment by afgane** [comment]
Is this breaking for you without these changes? If it is, I don't think it's due to a wrong path. Task [`Download bedtools source`](https://github.com/galaxyproject/ansible-trackster/pull/1/files#diff-4ae3980c56d3a3bd6dafed960d574343L25) downloads the file to `/tmp/bedtools2.tar.gz`, which when extracted simply goes into `/tmp/bedfiles2` dir so adding a version throws the whole thing off.

**Comment by nuwang** [comment]
Yes. The latest archive extracts to a path with the version name in the folder (it appears to contain a nested folder). As a result, it breaks without the changes I've pushed.

**Comment by afgane** [comment]
It's definitely not what I'm seeing. In fact, it's the complete opposite where if the version is specified, it breaks: http://pastie.org/10407744

**Comment by nuwang** [comment]
I get the exact opposite error.

```
    openstack: TASK: [galaxyprojectdotorg.trackster | Extract bedtools source] ***************
    openstack: changed: [localhost]
    openstack:
    openstack: TASK: [galaxyprojectdotorg.trackster | Make bedtools] *************************
    openstack: failed: [localhost] => {"failed": true, "rc": 258}
    openstack: msg: cannot change to directory '/tmp/bedtools2': path does not exist
```

I think the bedtools version is different. Trackster default is 2.20.1?

**Comment by nuwang** [comment]
Yes, definitely a problem with the bedtools archive version. Shall I issue a new pull with the default bedtools version updated? (I've also removed the bedtools settings from the gvl playbook, so that the trackster setting takes precedence)

**Comment by afgane** [comment]
Ahh, OK - I had the version set at the playbook level to 2.24.0. The most recent version is 2.25.0 so I guess we can update to it in the role defaults. I can do that so you don't have to mess with a PR...

**Pull request closed without merging**
